language: php

php:
  - 8.2

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - composer test

services:
  - mysql

notifications:
  email: false